Project Advisor Meeting 3 PR
Aluthra2/codeu_project_2017 pull request #26
Opened 2017-05-18 08:28 UTC by Aluthra2

2017-05-18 08:28 UTC, Aluthra2 commented
Hi Elmer! Please see the WorkDoneSoFar.txt to see what we have done so far.

2017-05-19 14:49 UTC, elmer-garduno requested changes

2017-05-19 14:49 UTC, elmer-garduno commented on WorkDoneSoFar.txt
> +Aman's Work:
It would be great to keep the history here and make the log additive instead.

2017-05-19 14:49 UTC, elmer-garduno commented on src/codeu/chat/client/ClientMessage.java
> +     if(mess.isEmpty() == false){
Please fix the style on this block:

```
     if(mess.isEmpty() == false){
       for(Message m : mess){
         System.out.println(" Time: " + m.creation + " Content "  + m.content);}
       }  else {
         System.out.println("User has no messages to display");
       }
    }
```

2017-05-19 14:49 UTC, elmer-garduno commented on src/codeu/chat/client/ClientMessage.java
>      if (m == null) {
Invert this if statement `if (m != null)`

2017-05-19 14:49 UTC, elmer-garduno commented on src/codeu/chat/client/Controller.java
> +
Please make style consistent here "2 space indentation"

2017-05-19 14:49 UTC, elmer-garduno commented on src/codeu/chat/client/commandline/Chat.java
> +        signInUser(tokenScanner.next());
Why did this changed?

2017-05-19 14:49 UTC, elmer-garduno commented on src/codeu/chat/client/commandline/Chat.java
> -      if (!tokenScanner.hasNext()) {
Indentation on this block shouldn't have changed

2017-05-24 06:02 UTC, merged