Project review
Aluthra2/codeu_project_2017 pull request #7
Opened 2017-04-06 15:32 UTC by Aluthra2

Combined All Branches into one Branch For Review.

2017-04-06 15:42 UTC, elmer-garduno commented
Thanks! I'll work on this branch.

2017-04-06 18:22 UTC, elmer-garduno commented
Can you please update the description to describe what these changes achieve, in particular which aspects of the design are being addressed.

2017-04-06 18:40 UTC, elmer-garduno requested changes
It will probably be a good idea to remove all the .idea files from the commit. Unless you are sharing these among all team members?

2017-04-07 02:44 UTC, Aluthra2 commented
I added a WorkDoneSoFar.txt file to explain the changes each of us made. Laura and Cristina will edit and push the document to the repository ASAP.

2017-04-07 02:45 UTC, Aluthra2 commented
For the .idea files, I'm not sure if Laura needs those files for her code (they're hers), so I'll let her know about those and if she doesn't need them, we could delete them.

2017-04-07 17:31 UTC, elmer-garduno requested changes
Please take a look the comments below, and please remove the .idea files so the scope of the change is clear.

2017-04-07 17:31 UTC, elmer-garduno commented on src/codeu/chat/client/ClientConversation.java
> +    //delete this conversation
Please remove un-used code.

2017-04-07 17:31 UTC, elmer-garduno commented on test/codeu/chat/client/ClientMessageTest.java
> + /*
Please add the actual test.

2017-04-07 17:31 UTC, elmer-garduno commented on src/codeu/chat/client/commandline/Chat.java
> +import codeu.chat.client.*;
Avoid import * to preserve  the namespace context.

2017-04-07 17:31 UTC, elmer-garduno commented on src/codeu/chat/common/Time.java
Why is this change on time needed?

2017-04-07 17:31 UTC, elmer-garduno commented on src/codeu/chat/util/Serializers.java
> +        out.write(0xFF & (value >>> i));
Do you have unit tests for this. Please write a test for the original behavior and make sure the new behavior preserves it.

2017-04-07 17:31 UTC, elmer-garduno commented on src/codeu/chat/util/Serializers.java
> +
Remove extra line.

2017-04-07 17:31 UTC, elmer-garduno commented on src/codeu/chat/util/Serializers.java
> +  public static final Serializer<Long> LONG = new Serializer<Long>() {
What does this accomplishes please add doscstring.

2017-04-07 22:27 UTC, Aluthra2 commented on src/codeu/chat/util/Serializers.java
> +
Just Committed the change.

2017-04-07 23:31 UTC, elmer-garduno requested changes

2017-04-07 23:31 UTC, elmer-garduno commented on src/codeu/chat/client/ClientMessage.java
> +      conversationContents.remove(msg);
Message should implement equals and hashCode for it to be comparable to the messages on the list.

Please see: implementing equals and hashCode on Effective Java (2nd Edition): Joshua Bloch.

2017-04-07 23:31 UTC, elmer-garduno commented on src/codeu/chat/client/ClientMessage.java
> +    if(conversationContents.contains(msg)) {
Both contains and remove will take linear time, consider replacing with a hash map implementation, be aware that HashMaps are unordered so might need to use an ordered hash map.

See: https://github.com/google/guava for advanced collection libraries.

2017-04-07 23:31 UTC, elmer-garduno commented on src/codeu/chat/client/ClientUser.java
> +    if(usersById.containsValue(name)){
First fetch the user from the name: user map then remove using the id.

2017-04-07 23:31 UTC, elmer-garduno commented on test/codeu/chat/client/ClientMessageTest.java
> +  public void testAddMessage() {
You can use mocks for the ConnectionSource since you don't want the tests to connect to the server.

See: http://site.mockito.org/

2017-04-17 04:04 UTC, Aluthra2 commented on src/codeu/chat/client/commandline/Chat.java
> +import codeu.chat.client.*;
Fixed.

2017-04-17 04:08 UTC, Aluthra2 commented on src/codeu/chat/client/ClientUser.java
> +    if(usersById.containsValue(name)){
On the timeline, I will be handling that implementation this week.

2017-04-17 04:34 UTC, Aluthra2 commented on src/codeu/chat/util/Serializers.java
> +        out.write(0xFF & (value >>> i));
Google's main repo addition

2017-04-17 04:34 UTC, Aluthra2 commented on src/codeu/chat/common/Time.java
Google's main repo addition

2017-04-24 22:27 UTC, lromeros commented on src/codeu/chat/client/ClientMessage.java
> +      conversationContents.remove(msg);
Implemented in new work.

2017-04-25 00:33 UTC, Aluthra2 commented on src/codeu/chat/client/ClientConversation.java
> +    //delete this conversation
Added TODO for Laura

2017-04-25 00:34 UTC, Aluthra2 commented on test/codeu/chat/client/ClientMessageTest.java
> + /*
Added TODO for Laura

2017-04-25 00:35 UTC, Aluthra2 commented on src/codeu/chat/util/Serializers.java
> +  public static final Serializer<Long> LONG = new Serializer<Long>() {
Google's main repo addition

2017-04-25 00:36 UTC, Aluthra2 commented on src/codeu/chat/client/ClientUser.java
> +    if(usersById.containsValue(name)){
I have it implemented, it will be in the next PR.

2017-04-25 00:39 UTC, Aluthra2 commented on src/codeu/chat/client/ClientMessage.java
> +    if(conversationContents.contains(msg)) {
Added a TODO for Laura.

2017-04-25 00:41 UTC, Aluthra2 commented on test/codeu/chat/client/ClientMessageTest.java
> +import codeu.chat.common.*;
Laura, which file in common did you specifically need? @lromeros

2017-04-25 00:43 UTC, Aluthra2 commented on test/codeu/chat/client/ClientMessageTest.java
> +  public void testAddMessage() {
Added a TODO for Laura.

2017-04-25 05:46 UTC, elmer-garduno approved these changes
Good to merge for now, make sure to address the TODOS on followup CL

2017-04-25 05:46 UTC, elmer-garduno commented on src/codeu/chat/client/ClientUser.java
> +  private static Store<String, User> usersByName = new Store<>(String.CASE_INSENSITIVE_ORDER);
Let's discuss latter why you need to use static here.

2017-04-25 21:01 UTC, lromeros commented on test/codeu/chat/client/ClientMessageTest.java
> +import codeu.chat.common.*;
This file is still a work in progress, will clean up shortly.

2017-04-26 00:09 UTC, merged